os:
- linux
cache:
  directories:
  - "$HOME/.composer/cache"
language: php
php:
- 7.2
before_script:
- cp .env.production .env
- php artisan key:generate
- mysql -e 'CREATE DATABASE assignment4 IF NOT EXIST;'
- php artisan migrate
- pgp artisan db:seed
services:
- mysql
install:
- composer install
script:
- phpunit --configuration phpunit.xml --coverage-text
deploy:
  provider: azure_web_apps
  verbose: true
notifications:
  email:
    recipients: tom_1995@msn.com
