os:
- linux
cache:
  directories:
  - "$HOME/.composer/cache"
language: php
php:
- 7.2
before_script:
- cp .env.production .env
- php artisan key:generate
- mysql -e 'CREATE DATABASE IF NOT EXISTS assignment4;'
- php artisan migrate
- php artisan db:seed
services:
- mysql
install:
- composer install
script:
- phpunit --configuration phpunit.xml --coverage-text
- php artisan migrate:refresh --seed
deploy:
  provider: azure_web_apps
  verbose: true
  username: "Smide"
  password: "ABCabc123!!!"
  site: "smide-app"
notifications:
  email:
    recipients: tom_1995@msn.com
